service/routes.py

provide API information for the base url '/'

update base url endpoint

---

service/routes.py
tests/test_routes.py

Create list all wishlists route

create list wishlists route

---

service/routes.py
tests/test_routes.py
tests/test_wishlist.py

add read wishlist endpoint

---

service/routes.py
tests/test_routes.py
tests/test_wishlist.py
tests/test_wishlist_item.py

Implemented “Add item to wishlist”
Add exception test cases of creating wishlists.

Add item to wishlist

---

service/routes.py
tests/test_routes.py
tests/test_wishlist.py

add list_all_wishlistitems endpoint

add list_all_wishlistitems endpoint

---

service/routes.py
tests/test_routes.py
tests/test_wishlist_item.py

added api for reading an item from the wishlist

---

service/routes.py
tests/test_routes.py
tests/test_wishlist_item.py

Create "delete items API"
Cannot pass all test cases because lack of read item API.

add delete items API

---

service/routes.py
tests/test_routes.py
tests/test_wishlist.py

Modified delete endpoint for wishlist and wishlist_items

---

service/models/wishlist_item.py
service/routes.py
tests/factories.py
tests/test_base.py
tests/test_routes.py
tests/test_wishlist.py
tests/test_wishlist_item.py

Refactored ./tests folder:
- Add test_base.py 
- Created TestBase class to solve "similar lines" problem
- Database_URI is now in this file
- TestBase contains setUp() and tearDown() functions of original test classes
- Modified test_routes.py, test_wishlist.py, and test_wishlist_item.py
- Class TestService, TestWishlist, and TestWishlistItem are now subclass of TestBase

Fixed lint problem. Refactored ./tests folder.

---

service/models/wishlist.py
tests/factories.py
tests/test_wishlist.py

modified 
service/models/wishlist.py
tests/test_wishlist.py
tests/test_routes.py

added createdDate and modifiedDate to Wishlist

---

.vscode/settings.json
service/models/wishlist_item.py
tests/factories.py
tests/test_wishlist_item.py

- Add added_date and modified_date to WishlistItems:
- File Modified:
1. `wishlist_item.py`
2. `factories.py`
3. `test_wishlist_items.py`

add attrs to wishlistitem

---

service/routes.py
tests/test_routes.py

delete all wishlists for specific customer

delete all wishlists for specific customer

---

service/routes.py
tests/test_routes.py

Implemented feature "Sort by added date" (by @tzuanwang)
Bug Fix (by @Litou-lyh )
- services/routes.py
- tests/test_route.py
- Previous bug: cannot sort as wish
- Reason: Flask does not distinguish "/endpoint" and "/endpoint?order_by=123" and "/endpoint?order_by=456", the sort requests always call the list function
- Solution: Move sort by price and sort by date into LIST (GET /wishlists/{wishlist_id}/items), using query parameters.

Sort by added date

---

README.md

Update README file for the following new endpoints:
1. Search for wishlists
2. Sort wishlists
3. Search items in a wishlist
4. Delete all wishlists
5. Move a item between wishlists

update new endpoints

---

Dockerfile
k8s/deployment.yaml
k8s/ingress.yml
k8s/postgres.yaml
k8s/pv.yaml
k8s/secret.yaml
k8s/service.yaml

deployed in kubernetes cluster

---

README.md
k8s/deployment.yaml
service/routes.py
tests/test_routes.py

#72 
added health endpoint in routes

added health endpoint

---

features/steps/web_steps.py
features/steps/wishlist_steps.py
features/wishlists.feature
service/models/wishlist_item.py
service/routes.py
service/static/index.html
service/static/js/rest_api.js
tests/test_routes.py

Update two files to create "create wishlist" user interface:
1. wishlists.feature
2. rest_api.js

Create wishlist UI

---

features/steps/web_steps.py
features/wishlists.feature
service/static/js/rest_api.js

Update wishlist UI

---

features/wishlists.feature
service/static/js/rest_api.js

ui_retrieve_wishlist_item

---

features/wishlists.feature
service/static/js/rest_api.js

ui-update-wishlistitem

---

features/wishlists.feature
service/static/js/rest_api.js

ui_delete_wishlistitem

---

features/wishlists.feature
service/static/js/rest_api.js

ui_delete_all_wishlists_by_customer_id

ui_delete_all_wishlists_by_customer_id

---

features/wishlists.feature
service/static/index.html
service/static/js/rest_api.js

UI search filtered wishlist item

UI search filtered wishlist item

---

service/__init__.py
service/models/wishlist.py
service/models/wishlist_item.py
service/routes.py
service/static/js/rest_api.js
tests/test_routes.py

Modified files:
- `service/__init__.py`: added restx api initialization
- `models/wishlist.py`: added checks for empty fields
- `models/wishlist_item.py`: added checks for empty fields

add restx initialization; modified deserialization to check empty fields

---

features/wishlists.feature

fix delete wishlist by customer id

fix delete wishlist by customer id

---

features/wishlists.feature
service/static/index.html
service/static/js/rest_api.js

implemented sort and order

---

service/static/index.html
service/static/js/rest_api.js

 implemented UI
